In [1]:
import pickle
import scipy.io
import numpy as np
# 读取pkl文件


In [2]:
with open('F:/jupyter/semantic/The-implementations-of-DeepSC/data/txt/test_data.pkl', 'rb') as f:
    data = pickle.load(f)
    
print(len(data))

7347


In [4]:
data=scipy.io.loadmat('./output/SNR=18.mat')
data = data['msgOutBytes']

In [5]:
print(data)

[[1 0 1 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 1 ... 0 0 0]
 [1 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 0]]


In [6]:

dimen = np.array(data).shape
print(dimen)


(1012, 8)


In [7]:
print(data[0],data[1],data[2])

[1 0 1 1 0 0 0 0] [0 0 0 1 1 0 0 0] [1 0 0 0 0 0 0 0]
